version: "3.3"

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - /home/configs/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - "3001:3000"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - "6612:6610"
    command: ["python3", "app/main.py"]

  # New registry service
  registry:
    image: registry:latest
    container_name: docker-reg
    ports:
      - "5000:5000"
    volumes:
      - /home/configs/docker-reg:/var/lib/registry

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: docker-registry-ui
    ports:
      - "8080:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-reg
      ENV_DOCKER_REGISTRY_PORT: 5000
